version: '3.4'

services:
  fluentd:
    image: fluent/fluentd
    build:
      context: .
      dockerfile: docker/fluentd/Dockerfile
    volumes:
      - './:/app'
    expose:
      - 24224

  elasicsearch:
    image: elasticsearch:6.5.0
    volumes:
      - './:/app'

  kibana:
    image: kibana:6.5.0
    ports:
      - "5601:5601"
    volumes:
      - './:/app'
