version: '3.4'

services:
  fluentd:
    build: ./docker/fluentd
    volumes:
      - ./docker/fluentd:/fluentd/etc
    networks:
      default:
      docker-monitoring:
        aliases: [fluentd]

  elasticsearch:
    image: elasticsearch:6.5.0

  kibana:
    image: kibana:6.5.0
    ports:
      - "5601:5601"

networks:
  docker-monitoring:
    external: true
