version: '3.4'

services:
  fluentd:
    image: fluent/fluentd
    build:
      context: .
      dockerfile: docker/fluentd/Dockerfile
    volumes:
      - './:/app'

  elasicsearch:
    image: elasticsearch:6.5.0
    volumes:
      - './:/app'

  kibana:
    image: kibana:6.5.0
    volumes:
      - './:/app'
